name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  buildwinandmacos:
    env:
      GOFLAGS: -modcacherw
    runs-on: macos-14
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          cache: true
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/macos/libs
            ${{ github.workspace }}/windows/libs
          key: ${{ runner.os }}-libs-${{ hashFiles('**/go.sum') }}
      - name: Build for macOS
        run: cd macos && sudo ./build.sh ${{ github.ref_name }}
      - name: Copy macOS installer to default working directory
        run: cp macos/target/WirePod-${{ github.ref_name }}.dmg .
      - name: Build for Windows
        run: cd windows && sudo ./build-installer.sh ${{ github.ref_name }} && sudo ./build.sh
      - name: Copy Windows installer to default working directory
        run: cp windows/wire-pod-win-amd64.zip . && cp windows/WirePodInstaller-${{ github.ref_name }}.exe .
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            WirePod-${{ github.ref_name }}.dmg
            WirePodInstaller-${{ github.ref_name }}.exe
            wire-pod-win-amd64.zip
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: WirePod-${{ github.ref_name }}.dmg
          path: WirePod-${{ github.ref_name }}.dmg
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WirePod-${{ github.ref_name }}-windows
          path: |
            WirePodInstaller-${{ github.ref_name }}.exe
            wire-pod-win-amd64.zip
  builddebs:
    env:
      GOFLAGS: -modcacherw
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: false
      - name: Build .debs
        run: cd debian && ./createdeb.sh ${{ github.ref_name }}
      - name: Copy final .debs to working directory
        run: cp debian/final/wirepod*.deb .
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            wirepod_amd64-${{ github.ref_name }}.deb
            wirepod_arm64-${{ github.ref_name }}.deb
            wirepod_armhf-${{ github.ref_name }}.deb
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wirepod-${{ github.ref_name }}-debian
          path: |
            wirepod_amd64-${{ github.ref_name }}.deb
            wirepod_arm64-${{ github.ref_name }}.deb
            wirepod_armhf-${{ github.ref_name }}.deb
